;;; counsel-codesearch-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from counsel-codesearch.el

(autoload 'counsel-codesearch "counsel-codesearch" "\
Call the \"csearch\" shell command.

INITIAL-INPUT can be given as the initial minibuffer input." t)
(register-definition-prefixes "counsel-codesearch" '("counsel-codesearch--"))

;;; End of scraped data

(provide 'counsel-codesearch-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; counsel-codesearch-autoloads.el ends here
